/******************************************************************************

                              Online C++ Compiler.
               Code, Compile, Run and Debug C++ program online.
Write your code in this editor and press "Run" button to compile and execute it.

*******************************************************************************/

#include <iostream>

using namespace std;

int main(){
    
string name;
int ap;
int cp;
int na;
int nc;
int tot;
int obt;
int per;
int pro;



cout<<"ENTER YOUR MOVIE NAME:";
cin>>name;
cout<<"Enter adult ticket price: ";
cin>>ap;
cout<<"ENTER CHILD TICKET PRICE: ";
cin>>cp;
cout<<"Amount of Adult ticket sold: ";
cin>>na;
cout<<"Amount of Child ticket sold: ";
cin>>nc;
tot =(ap*na)+(cp*nc);
cout<<"Enter the percentage of amount to be denoted to charity: ";
cin>>per;
obt =(per*tot)/100;
cout<<"Total amount generated by sold tickets is: "<<tot<<endl;

pro =tot-obt;
cout<<"Proit after denoting from total amount is: "<<pro;









}
